# -*- coding: utf-8 -*-
"""Analise de Dados Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tybYmDIrLJ5nfTaPS_m5NqEDoJtFFEKn

# Desafio:

Você trabalha em uma grande empresa de Cartão de Crédito e o diretor da empresa percebeu que o número de clientes que cancelam seus cartões tem aumentado significativamente, causando prejuízos enormes para a empresa

O que fazer para evitar isso? Como saber as pessoas que têm maior tendência a cancelar o cartão?

# O que temos:

Temos 1 base de dados com informações dos clientes, tanto clientes atuais quanto clientes que cancelaram o cartão

Download da Base de Dados: Botão na página

Referência: https://www.kaggle.com/sakshigoyal7/credit-card-customers
"""

import pandas as pdp
tabela = pdp.read_csv("/content/drive/MyDrive/ClientesBanco.csv", encoding="latin1")
tabela = tabela.drop("CLIENTNUM", axis=1)
display(tabela)

"""# agora vamos tratar valores vazios e exebir um resumo das colunas da base de dados

"""

tabela = tabela.dropna()
display(tabela.info())

display(tabela.describe().round(1))

"""# vamos avaliar como estar a divião entre clientes x  cancelados"""

qtde_categoria = tabela["Categoria"].value_counts()
display(qtde_categoria)

qtde_categoria_perc = tabela["Categoria"].value_counts(normalize=True )
display(qtde_categoria_perc)

"""# temos varias formas de descobrir o motivo de cancelamento
- podemos olhar a comparação entre clientes e cancelados em cada uma das nossas colunas de base dados, para ver se essas imformações traz algum insight novo para a gente
"""

import plotly.express as px

for coluna in tabela:

  grafico = px.histogram(tabela, x=coluna, color="Categoria")
  grafico.show()

from google.colab import drive
drive.mount('/content/drive')

